using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OptionCSMSAutomationPlayWright
{
    public class EnumCommand
    {
        public enum ControlID
        {
            txtEmail,
            li_dashboard,
            li_view_myclass,
            li_logout,
            li_google_calendar,
            li_my_billing_accounts,
            li_Learning_Management_Standard,
            li_view_google_calendar,
            li_masscard_requests,
            li_my_files,
            li_inbox_message,
            li_my_optionc_online_training,
            li_conferences_list,
            li_professional_development,
            li_my_user_profile,
            li_personal_options,
            li_my_general_settings,
            li_diocesedata_index,
            li_staff_schedule,
            li_user_resources,
            li_acr_about,
            li_medication_dashboard,
            li_about_conduct_forms,
            li_view_announcement,
            li_basic_settings,
            li_class_capacities_view,
            li_eforms_list,
            li_billing_ledger_view,
            li_mealsitems_view,
            li_skill_scales,
            li_gpa_dashboard,
            li_user_permissions,
            li_contact_information,
            li_staff_attendance,
            li_community_suppport,
            li_data_update_tools,
            li_walkthroughs,
            li_securemessage_view,
            li_EndOfYearGuide_view,
            li_studentranscript_index,
            li_terranova_index,
            li_staff_evaluation_view,
            li_student_conduct,
            li_administration,
            li_schools,
            li_reports_list,
            li_reports,
            li_report_card_manager,
            li_site_map,
            li_faq_view,
            li_resource_library,
            li_onlinetraining_view,
            li_trainingvideos_view,
            li_implementationguide,
            li_familymoduleupload_view,
            li_contactinformation_view,
            li_staff_eforms_list,
            li_support,
            li_catholic_content,
            li_my_settings,
            li_my_attendance_settings,
            li_assignment_weightage,
            li_my_lessonplan_settings,
            li_my_school_meals_settings,
            li_directories,
            li_directories_dashboard,
            li_students_details,
            li_staff_details,
            li_relatives_details,
            li_family_details,
            li_prospects_details,
            li_students_alumni,
            li_disabled_user,
            li_user_profile,
            li_group_list,
            li_parish_details,
            li_public_school_manager,
            li_medical_provider_list,
            li_photo_upload,
            li_class_administration,
            li_edfi_list,
            li_new_view,
            li_associate_sections_view,
            li_student_attendance_status_list,
            li_copyclasses_withinyear_view,
            li_emergency_drills,
            li_term_manager,
            li_term_scheduling_view,
            li_communication_dashboard,
            li_view_calendar,
            li_view_filelibrary,
            li_parentalerts_about,
            li_course_catalog_view,
            li_days_off,
            li_selectterm,
            li_building_facility_view,
            li_add_section,
            li_scales_dashboard,
            li_alpha_scales,
            li_comment_codes,
            li_grade_scales,
            li_learner_behaviors,
            li_learner_behavior_scales,
            li_skill_list,
            li_permissions,
            li_admin_permissions,
            li_class_permissions,
            li_profile_student_permissions,
            li_report_permissions,
            li_optionc_calendar

        }


        public enum ControlName
        {
            txtName
        }


    }
}